name: Swift build checks

on:
  push:
    branches: [ "main" , "development"]
  pull_request:
    branches: [ "main" , "development" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Get swift version
      run: swift --version

    - name: Build
      run: swift build -v

    - name: Run tests
      run: swift test -v

    - name: Project Directory
      run: echo ${GITHUB_WORKSPACE}

    - name: Run SwiftLint in strict mode
      run: swiftlint lint --strict --path ${GITHUB_WORKSPACE}
